# Generated by Django 2.2.2 on 2019-06-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('Mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('Msg_id', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('From', models.CharField(max_length=100)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
