# Generated by Django 2.2.2 on 2019-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
